const countries = [
{label:"Afganistán",label2:"Afghanistan",label3:"Afghanistan",code:"AF",code3:"AFG",code4:"93"},
{label:"Albania",label2:"Albania",label3:"Albanie",code:"AL",code3:"ALB",code4:"355"},
{label:"Alemania",label2:"Germany",label3:"Allemagne",code:"DE",code3:"DEU",code4:"49"},
{label:"Andorra",label2:"Andorra",label3:"Andorra",code:"AD",code3:"AND",code4:"376"},
{label:"Angola",label2:"Angola",label3:"Angola",code:"AO",code3:"AGO",code4:"244"},
{label:"Anguila",label2:"Anguilla",label3:"Anguilla",code:"AI",code3:"AIA",code4:"1 264"},
{label:"Antártida",label2:"Antarctica",label3:"L'Antarctique",code:"AQ",code3:"ATA",code4:"672"},
{label:"Antigua y Barbuda",label2:"Antigua and Barbuda",label3:"Antigua et Barbuda",code:"AG",code3:"ATG",code4:"1 268"},
{label:"Arabia Saudita",label2:"Saudi Arabia",label3:"Arabie Saoudite",code:"SA",code3:"SAU",code4:"966"},
{label:"Argelia",label2:"Algeria",label3:"Algérie",code:"DZ",code3:"DZA",code4:"213"},
{label:"Argentina",label2:"Argentina",label3:"Argentine",code:"AR",code3:"ARG",code4:"54"},
{label:"Armenia",label2:"Armenia",label3:"L'Arménie",code:"AM",code3:"ARM",code4:"374"},
{label:"Aruba",label2:"Aruba",label3:"Aruba",code:"AW",code3:"ABW",code4:"297"},
{label:"Australia",label2:"Australia",label3:"Australie",code:"AU",code3:"AUS",code4:"61"},
{label:"Austria",label2:"Austria",label3:"Autriche",code:"AT",code3:"AUT",code4:"43"},
{label:"Azerbaiyán",label2:"Azerbaijan",label3:"L'Azerbaïdjan",code:"AZ",code3:"AZE",code4:"994"},
{label:"Bélgica",label2:"Belgium",label3:"Belgique",code:"BE",code3:"BEL",code4:"32"},
{label:"Bahamas",label2:"Bahamas",label3:"Bahamas",code:"BS",code3:"BHS",code4:"1 242"},
{label:"Bahrein",label2:"Bahrain",label3:"Bahreïn",code:"BH",code3:"BHR",code4:"973"},
{label:"Bangladesh",label2:"Bangladesh",label3:"Bangladesh",code:"BD",code3:"BGD",code4:"880"},
{label:"Barbados",label2:"Barbados",label3:"Barbade",code:"BB",code3:"BRB",code4:"1 246"},
{label:"Belice",label2:"Belize",label3:"Belize",code:"BZ",code3:"BLZ",code4:"501"},
{label:"Benín",label2:"Benin",label3:"Bénin",code:"BJ",code3:"BEN",code4:"229"},
{label:"Bhután",label2:"Bhutan",label3:"Le Bhoutan",code:"BT",code3:"BTN",code4:"975"},
{label:"Bielorrusia",label2:"Belarus",label3:"Biélorussie",code:"BY",code3:"BLR",code4:"375"},
{label:"Birmania",label2:"Myanmar",label3:"Myanmar",code:"MM",code3:"MMR",code4:"95"},
{label:"Bolivia",label2:"Bolivia",label3:"Bolivie",code:"BO",code3:"BOL",code4:"591"},
{label:"Bosnia y Herzegovina",label2:"Bosnia and Herzegovina",label3:"Bosnie-Herzégovine",code:"BA",code3:"BIH",code4:"387"},
{label:"Botsuana",label2:"Botswana",label3:"Botswana",code:"BW",code3:"BWA",code4:"267"},
{label:"Brasil",label2:"Brazil",label3:"Brésil",code:"BR",code3:"BRA",code4:"55"},
{label:"Brunéi",label2:"Brunei",label3:"Brunei",code:"BN",code3:"BRN",code4:"673"},
{label:"Bulgaria",label2:"Bulgaria",label3:"Bulgarie",code:"BG",code3:"BGR",code4:"359"},
{label:"Burkina Faso",label2:"Burkina Faso",label3:"Burkina Faso",code:"BF",code3:"BFA",code4:"226"},
{label:"Burundi",label2:"Burundi",label3:"Burundi",code:"BI",code3:"BDI",code4:"257"},
{label:"Cabo Verde",label2:"Cape Verde",label3:"Cap-Vert",code:"CV",code3:"CPV",code4:"238"},
{label:"Camboya",label2:"Cambodia",label3:"Cambodge",code:"KH",code3:"KHM",code4:"855"},
{label:"Camerún",label2:"Cameroon",label3:"Cameroun",code:"CM",code3:"CMR",code4:"237"},
{label:"Canadá",label2:"Canada",label3:"Canada",code:"CA",code3:"CAN",code4:"1"},
{label:"Chad",label2:"Chad",label3:"Tchad",code:"TD",code3:"TCD",code4:"235"},
{label:"Chile",label2:"Chile",label3:"Chili",code:"CL",code3:"CHL",code4:"56"},
{label:"China",label2:"China",label3:"Chine",code:"CN",code3:"CHN",code4:"86"},
{label:"Chipre",label2:"Cyprus",label3:"Chypre",code:"CY",code3:"CYP",code4:"357"},
{label:"Ciudad del Vaticano",label2:"Vatican City State",label3:"Cité du Vatican",code:"VA",code3:"VAT",code4:"39"},
{label:"Colombia",label2:"Colombia",label3:"Colombie",code:"CO",code3:"COL",code4:"57"},
{label:"Comoras",label2:"Comoros",label3:"Comores",code:"KM",code3:"COM",code4:"269"},
{label:"República del Congo",label2:"Republic of the Congo",label3:"République du Congo",code:"CG",code3:"COG",code4:"242"},
{label:"República Democrática del Congo",label2:"Democratic Republic of the Congo",label3:"République démocratique du Congo",code:"CD",code3:"COD",code4:"243"},
{label:"Corea del Norte",label2:"North Korea",label3:"Corée du Nord",code:"KP",code3:"PRK",code4:"850"},
{label:"Corea del Sur",label2:"South Korea",label3:"Corée du Sud",code:"KR",code3:"KOR",code4:"82"},
{label:"Costa de Marfil",label2:"Ivory Coast",label3:"Côte-d'Ivoire",code:"CI",code3:"CIV",code4:"225"},
{label:"Costa Rica",label2:"Costa Rica",label3:"Costa Rica",code:"CR",code3:"CRI",code4:"506"},
{label:"Croacia",label2:"Croatia",label3:"Croatie",code:"HR",code3:"HRV",code4:"385"},
{label:"Cuba",label2:"Cuba",label3:"Cuba",code:"CU",code3:"CUB",code4:"53"},
{label:"Curazao",label2:"Curaçao",label3:"Curaçao",code:"CW",code3:"CWU",code4:"5999"},
{label:"Dinamarca",label2:"Denmark",label3:"Danemark",code:"DK",code3:"DNK",code4:"45"},
{label:"Dominica",label2:"Dominica",label3:"Dominique",code:"DM",code3:"DMA",code4:"1 767"},
{label:"Ecuador",label2:"Ecuador",label3:"Equateur",code:"EC",code3:"ECU",code4:"593"},
{label:"Egipto",label2:"Egypt",label3:"Egypte",code:"EG",code3:"EGY",code4:"20"},
{label:"El Salvador",label2:"El Salvador",label3:"El Salvador",code:"SV",code3:"SLV",code4:"503"},
{label:"Emiratos Árabes Unidos",label2:"United Arab Emirates",label3:"Emirats Arabes Unis",code:"AE",code3:"ARE",code4:"971"},
{label:"Eritrea",label2:"Eritrea",label3:"Erythrée",code:"ER",code3:"ERI",code4:"291"},
{label:"Eslovaquia",label2:"Slovakia",label3:"Slovaquie",code:"SK",code3:"SVK",code4:"421"},
{label:"Eslovenia",label2:"Slovenia",label3:"Slovénie",code:"SI",code3:"SVN",code4:"386"},
{label:"España",label2:"Spain",label3:"Espagne",code:"ES",code3:"ESP",code4:"34"},
{label:"Estados Unidos de América",label2:"United States of America",label3:"États-Unis d'Amérique",code:"US",code3:"USA",code4:"1"},
{label:"Estonia",label2:"Estonia",label3:"L'Estonie",code:"EE",code3:"EST",code4:"372"},
{label:"Etiopía",label2:"Ethiopia",label3:"Ethiopie",code:"ET",code3:"ETH",code4:"251"},
{label:"Filipinas",label2:"Philippines",label3:"Philippines",code:"PH",code3:"PHL",code4:"63"},
{label:"Finlandia",label2:"Finland",label3:"Finlande",code:"FI",code3:"FIN",code4:"358"},
{label:"Fiyi",label2:"Fiji",label3:"Fidji",code:"FJ",code3:"FJI",code4:"679"},
{label:"Francia",label2:"France",label3:"France",code:"FR",code3:"FRA",code4:"33"},
{label:"Gabón",label2:"Gabon",label3:"Gabon",code:"GA",code3:"GAB",code4:"241"},
{label:"Gambia",label2:"Gambia",label3:"Gambie",code:"GM",code3:"GMB",code4:"220"},
{label:"Georgia",label2:"Georgia",label3:"Géorgie",code:"GE",code3:"GEO",code4:"995"},
{label:"Ghana",label2:"Ghana",label3:"Ghana",code:"GH",code3:"GHA",code4:"233"},
{label:"Gibraltar",label2:"Gibraltar",label3:"Gibraltar",code:"GI",code3:"GIB",code4:"350"},
{label:"Granada",label2:"Grenada",label3:"Grenade",code:"GD",code3:"GRD",code4:"1 473"},
{label:"Grecia",label2:"Greece",label3:"Grèce",code:"GR",code3:"GRC",code4:"30"},
{label:"Groenlandia",label2:"Greenland",label3:"Groenland",code:"GL",code3:"GRL",code4:"299"},
{label:"Guadalupe",label2:"Guadeloupe",label3:"Guadeloupe",code:"GP",code3:"GLP",code4:"590"},
{label:"Guam",label2:"Guam",label3:"Guam",code:"GU",code3:"GUM",code4:"1 671"},
{label:"Guatemala",label2:"Guatemala",label3:"Guatemala",code:"GT",code3:"GTM",code4:"502"},
{label:"Guayana Francesa",label2:"French Guiana",label3:"Guyane française",code:"GF",code3:"GUF",code4:"594"},
{label:"Guernsey",label2:"Guernsey",label3:"Guernesey",code:"GG",code3:"GGY",code4:"44"},
{label:"Guinea",label2:"Guinea",label3:"Guinée",code:"GN",code3:"GIN",code4:"224"},
{label:"Guinea Ecuatorial",label2:"Equatorial Guinea",label3:"Guinée Equatoriale",code:"GQ",code3:"GNQ",code4:"240"},
{label:"Guinea-Bissau",label2:"Guinea-Bissau",label3:"Guinée-Bissau",code:"GW",code3:"GNB",code4:"245"},
{label:"Guyana",label2:"Guyana",label3:"Guyane",code:"GY",code3:"GUY",code4:"592"},
{label:"Haití",label2:"Haiti",label3:"Haïti",code:"HT",code3:"HTI",code4:"509"},
{label:"Honduras",label2:"Honduras",label3:"Honduras",code:"HN",code3:"HND",code4:"504"},
{label:"Hong kong",label2:"Hong Kong",label3:"Hong Kong",code:"HK",code3:"HKG",code4:"852"},
{label:"Hungría",label2:"Hungary",label3:"Hongrie",code:"HU",code3:"HUN",code4:"36"},
{label:"India",label2:"India",label3:"Inde",code:"IN",code3:"IND",code4:"91"},
{label:"Indonesia",label2:"Indonesia",label3:"Indonésie",code:"ID",code3:"IDN",code4:"62"},
{label:"Irán",label2:"Iran",label3:"Iran",code:"IR",code3:"IRN",code4:"98"},
{label:"Irak",label2:"Iraq",label3:"Irak",code:"IQ",code3:"IRQ",code4:"964"},
{label:"Irlanda",label2:"Ireland",label3:"Irlande",code:"IE",code3:"IRL",code4:"353"},
{label:"Isla Bouvet",label2:"Bouvet Island",label3:"Bouvet Island",code:"BV",code3:"BVT",code4:""},
{label:"Isla de Man",label2:"Isle of Man",label3:"Ile de Man",code:"IM",code3:"IMN",code4:"44"},
{label:"Isla de Navidad",label2:"Christmas Island",label3:"Christmas Island",code:"CX",code3:"CXR",code4:"61"},
{label:"Isla Norfolk",label2:"Norfolk Island",label3:"Île de Norfolk",code:"NF",code3:"NFK",code4:"672"},
{label:"Islandia",label2:"Iceland",label3:"Islande",code:"IS",code3:"ISL",code4:"354"},
{label:"Islas Bermudas",label2:"Bermuda Islands",label3:"Bermudes",code:"BM",code3:"BMU",code4:"1 441"},
{label:"Islas Caimán",label2:"Cayman Islands",label3:"Iles Caïmans",code:"KY",code3:"CYM",code4:"1 345"},
{label:"Islas Cocos (Keeling)",label2:"Cocos (Keeling) Islands",label3:"Cocos (Keeling)",code:"CC",code3:"CCK",code4:"61"},
{label:"Islas Cook",label2:"Cook Islands",label3:"Iles Cook",code:"CK",code3:"COK",code4:"682"},
{label:"Islas de Åland",label2:"Åland Islands",label3:"Îles Åland",code:"AX",code3:"ALA",code4:"358"},
{label:"Islas Feroe",label2:"Faroe Islands",label3:"Iles Féro",code:"FO",code3:"FRO",code4:"298"},
{label:"Islas Georgias del Sur y Sandwich del Sur",label2:"South Georgia and the South Sandwich Islands",label3:"Géorgie du Sud et les Îles Sandwich du Sud",code:"GS",code3:"SGS",code4:"500"},
{label:"Islas Heard y McDonald",label2:"Heard Island and McDonald Islands",label3:"Les îles Heard et McDonald",code:"HM",code3:"HMD",code4:""},
{label:"Islas Maldivas",label2:"Maldives",label3:"Maldives",code:"MV",code3:"MDV",code4:"960"},
{label:"Islas Malvinas",label2:"Falkland Islands (Malvinas)",label3:"Iles Falkland (Malvinas)",code:"FK",code3:"FLK",code4:"500"},
{label:"Islas Marianas del Norte",label2:"Northern Mariana Islands",label3:"Iles Mariannes du Nord",code:"MP",code3:"MNP",code4:"1 670"},
{label:"Islas Marshall",label2:"Marshall Islands",label3:"Iles Marshall",code:"MH",code3:"MHL",code4:"692"},
{label:"Islas Pitcairn",label2:"Pitcairn Islands",label3:"Iles Pitcairn",code:"PN",code3:"PCN",code4:"870"},
{label:"Islas Salomón",label2:"Solomon Islands",label3:"Iles Salomon",code:"SB",code3:"SLB",code4:"677"},
{label:"Islas Turcas y Caicos",label2:"Turks and Caicos Islands",label3:"Iles Turques et Caïques",code:"TC",code3:"TCA",code4:"1 649"},
{label:"Islas Ultramarinas Menores de Estados Unidos",label2:"United States Minor Outlying Islands",label3:"États-Unis Îles mineures éloignées",code:"UM",code3:"UMI",code4:"246"},
{label:"Islas Vírgenes Británicas",label2:"Virgin Islands",label3:"Iles Vierges",code:"VG",code3:"VGB",code4:"1 284"},
{label:"Islas Vírgenes de los Estados Unidos",label2:"United States Virgin Islands",label3:"Îles Vierges américaines",code:"VI",code3:"VIR",code4:"1 340"},
{label:"Israel",label2:"Israel",label3:"Israël",code:"IL",code3:"ISR",code4:"972"},
{label:"Italia",label2:"Italy",label3:"Italie",code:"IT",code3:"ITA",code4:"39"},
{label:"Jamaica",label2:"Jamaica",label3:"Jamaïque",code:"JM",code3:"JAM",code4:"1 876"},
{label:"Japón",label2:"Japan",label3:"Japon",code:"JP",code3:"JPN",code4:"81"},
{label:"Jersey",label2:"Jersey",label3:"Maillot",code:"JE",code3:"JEY",code4:"44"},
{label:"Jordania",label2:"Jordan",label3:"Jordan",code:"JO",code3:"JOR",code4:"962"},
{label:"Kazajistán",label2:"Kazakhstan",label3:"Le Kazakhstan",code:"KZ",code3:"KAZ",code4:"7"},
{label:"Kenia",label2:"Kenya",label3:"Kenya",code:"KE",code3:"KEN",code4:"254"},
{label:"Kirguistán",label2:"Kyrgyzstan",label3:"Kirghizstan",code:"KG",code3:"KGZ",code4:"996"},
{label:"Kiribati",label2:"Kiribati",label3:"Kiribati",code:"KI",code3:"KIR",code4:"686"},
{label:"Kuwait",label2:"Kuwait",label3:"Koweït",code:"KW",code3:"KWT",code4:"965"},
{label:"Líbano",label2:"Lebanon",label3:"Liban",code:"LB",code3:"LBN",code4:"961"},
{label:"Laos",label2:"Laos",label3:"Laos",code:"LA",code3:"LAO",code4:"856"},
{label:"Lesoto",label2:"Lesotho",label3:"Lesotho",code:"LS",code3:"LSO",code4:"266"},
{label:"Letonia",label2:"Latvia",label3:"La Lettonie",code:"LV",code3:"LVA",code4:"371"},
{label:"Liberia",label2:"Liberia",label3:"Liberia",code:"LR",code3:"LBR",code4:"231"},
{label:"Libia",label2:"Libya",label3:"Libye",code:"LY",code3:"LBY",code4:"218"},
{label:"Liechtenstein",label2:"Liechtenstein",label3:"Liechtenstein",code:"LI",code3:"LIE",code4:"423"},
{label:"Lituania",label2:"Lithuania",label3:"La Lituanie",code:"LT",code3:"LTU",code4:"370"},
{label:"Luxemburgo",label2:"Luxembourg",label3:"Luxembourg",code:"LU",code3:"LUX",code4:"352"},
{label:"México",label2:"Mexico",label3:"Mexique",code:"MX",code3:"MEX",code4:"52"},
{label:"Mónaco",label2:"Monaco",label3:"Monaco",code:"MC",code3:"MCO",code4:"377"},
{label:"Macao",label2:"Macao",label3:"Macao",code:"MO",code3:"MAC",code4:"853"},
{label:"Macedônia",label2:"Macedonia",label3:"Macédoine",code:"MK",code3:"MKD",code4:"389"},
{label:"Madagascar",label2:"Madagascar",label3:"Madagascar",code:"MG",code3:"MDG",code4:"261"},
{label:"Malasia",label2:"Malaysia",label3:"Malaisie",code:"MY",code3:"MYS",code4:"60"},
{label:"Malawi",label2:"Malawi",label3:"Malawi",code:"MW",code3:"MWI",code4:"265"},
{label:"Mali",label2:"Mali",label3:"Mali",code:"ML",code3:"MLI",code4:"223"},
{label:"Malta",label2:"Malta",label3:"Malte",code:"MT",code3:"MLT",code4:"356"},
{label:"Marruecos",label2:"Morocco",label3:"Maroc",code:"MA",code3:"MAR",code4:"212"},
{label:"Martinica",label2:"Martinique",label3:"Martinique",code:"MQ",code3:"MTQ",code4:"596"},
{label:"Mauricio",label2:"Mauritius",label3:"Iles Maurice",code:"MU",code3:"MUS",code4:"230"},
{label:"Mauritania",label2:"Mauritania",label3:"Mauritanie",code:"MR",code3:"MRT",code4:"222"},
{label:"Mayotte",label2:"Mayotte",label3:"Mayotte",code:"YT",code3:"MYT",code4:"262"},
{label:"Micronesia",label2:"Estados Federados de",label3:"Federados Estados de",code:"FM",code3:"FSM",code4:"691"},
{label:"Moldavia",label2:"Moldova",label3:"Moldavie",code:"MD",code3:"MDA",code4:"373"},
{label:"Mongolia",label2:"Mongolia",label3:"Mongolie",code:"MN",code3:"MNG",code4:"976"},
{label:"Montenegro",label2:"Montenegro",label3:"Monténégro",code:"ME",code3:"MNE",code4:"382"},
{label:"Montserrat",label2:"Montserrat",label3:"Montserrat",code:"MS",code3:"MSR",code4:"1 664"},
{label:"Mozambique",label2:"Mozambique",label3:"Mozambique",code:"MZ",code3:"MOZ",code4:"258"},
{label:"Namibia",label2:"Namibia",label3:"Namibie",code:"NA",code3:"NAM",code4:"264"},
{label:"Nauru",label2:"Nauru",label3:"Nauru",code:"NR",code3:"NRU",code4:"674"},
{label:"Nepal",label2:"Nepal",label3:"Népal",code:"NP",code3:"NPL",code4:"977"},
{label:"Nicaragua",label2:"Nicaragua",label3:"Nicaragua",code:"NI",code3:"NIC",code4:"505"},
{label:"Niger",label2:"Niger",label3:"Niger",code:"NE",code3:"NER",code4:"227"},
{label:"Nigeria",label2:"Nigeria",label3:"Nigeria",code:"NG",code3:"NGA",code4:"234"},
{label:"Niue",label2:"Niue",label3:"Niou",code:"NU",code3:"NIU",code4:"683"},
{label:"Noruega",label2:"Norway",label3:"Norvège",code:"NO",code3:"NOR",code4:"47"},
{label:"Nueva Caledonia",label2:"New Caledonia",label3:"Nouvelle-Calédonie",code:"NC",code3:"NCL",code4:"687"},
{label:"Nueva Zelanda",label2:"New Zealand",label3:"Nouvelle-Zélande",code:"NZ",code3:"NZL",code4:"64"},
{label:"Omán",label2:"Oman",label3:"Oman",code:"OM",code3:"OMN",code4:"968"},
{label:"Países Bajos",label2:"Netherlands",label3:"Pays-Bas",code:"NL",code3:"NLD",code4:"31"},
{label:"Pakistán",label2:"Pakistan",label3:"Pakistan",code:"PK",code3:"PAK",code4:"92"},
{label:"Palau",label2:"Palau",label3:"Palau",code:"PW",code3:"PLW",code4:"680"},
{label:"Palestina",label2:"Palestine",label3:"La Palestine",code:"PS",code3:"PSE",code4:"970"},
{label:"Panamá",label2:"Panama",label3:"Panama",code:"PA",code3:"PAN",code4:"507"},
{label:"Papúa Nueva Guinea",label2:"Papua New Guinea",label3:"Papouasie-Nouvelle-Guinée",code:"PG",code3:"PNG",code4:"675"},
{label:"Paraguay",label2:"Paraguay",label3:"Paraguay",code:"PY",code3:"PRY",code4:"595"},
{label:"Perú",label2:"Peru",label3:"Pérou",code:"PE",code3:"PER",code4:"51"},
{label:"Polinesia Francesa",label2:"French Polynesia",label3:"Polynésie française",code:"PF",code3:"PYF",code4:"689"},
{label:"Polonia",label2:"Poland",label3:"Pologne",code:"PL",code3:"POL",code4:"48"},
{label:"Portugal",label2:"Portugal",label3:"Portugal",code:"PT",code3:"PRT",code4:"351"},
{label:"Puerto Rico",label2:"Puerto Rico",label3:"Porto Rico",code:"PR",code3:"PRI",code4:"1"},
{label:"Qatar",label2:"Qatar",label3:"Qatar",code:"QA",code3:"QAT",code4:"974"},
{label:"Reino Unido",label2:"United Kingdom",label3:"Royaume-Uni",code:"GB",code3:"GBR",code4:"44"},
{label:"República Centroafricana",label2:"Central African Republic",label3:"République Centrafricaine",code:"CF",code3:"CAF",code4:"236"},
{label:"República Checa",label2:"Czech Republic",label3:"République Tchèque",code:"CZ",code3:"CZE",code4:"420"},
{label:"República Dominicana",label2:"Dominican Republic",label3:"République Dominicaine",code:"DO",code3:"DOM",code4:"1 809"},
{label:"República de Sudán del Sur",label2:"South Sudan",label3:"Soudan du Sud",code:"SS",code3:"SSD",code4:"211"},
{label:"Reunión",label2:"Réunion",label3:"Réunion",code:"RE",code3:"REU",code4:"262"},
{label:"Ruanda",label2:"Rwanda",label3:"Rwanda",code:"RW",code3:"RWA",code4:"250"},
{label:"Rumanía",label2:"Romania",label3:"Roumanie",code:"RO",code3:"ROU",code4:"40"},
{label:"Rusia",label2:"Russia",label3:"La Russie",code:"RU",code3:"RUS",code4:"7"},
{label:"Sahara Occidental",label2:"Western Sahara",label3:"Sahara Occidental",code:"EH",code3:"ESH",code4:"212"},
{label:"Samoa",label2:"Samoa",label3:"Samoa",code:"WS",code3:"WSM",code4:"685"},
{label:"Samoa Americana",label2:"American Samoa",label3:"Les Samoa américaines",code:"AS",code3:"ASM",code4:"1 684"},
{label:"San Bartolomé",label2:"Saint Barthélemy",label3:"Saint-Barthélemy",code:"BL",code3:"BLM",code4:"590"},
{label:"San Cristóbal y Nieves",label2:"Saint Kitts and Nevis",label3:"Saint Kitts et Nevis",code:"KN",code3:"KNA",code4:"1 869"},
{label:"San Marino",label2:"San Marino",label3:"San Marino",code:"SM",code3:"SMR",code4:"378"},
{label:"San Martín (Francia)",label2:"Saint Martin (French part)",label3:"Saint-Martin (partie française)",code:"MF",code3:"MAF",code4:"1 599"},
{label:"San Pedro y Miquelón",label2:"Saint Pierre and Miquelon",label3:"Saint-Pierre-et-Miquelon",code:"PM",code3:"SPM",code4:"508"},
{label:"San Vicente y las Granadinas",label2:"Saint Vincent and the Grenadines",label3:"Saint-Vincent et Grenadines",code:"VC",code3:"VCT",code4:"1 784"},
{label:"Santa Elena",label2:"Ascensión y Tristán de Acuña",label3:"Ascensión y Tristan de Acuña",code:"SH",code3:"SHN",code4:"290"},
{label:"Santa Lucía",label2:"Saint Lucia",label3:"Sainte-Lucie",code:"LC",code3:"LCA",code4:"1 758"},
{label:"Santo Tomé y Príncipe",label2:"Sao Tome and Principe",label3:"Sao Tomé et Principe",code:"ST",code3:"STP",code4:"239"},
{label:"Senegal",label2:"Senegal",label3:"Sénégal",code:"SN",code3:"SEN",code4:"221"},
{label:"Serbia",label2:"Serbia",label3:"Serbie",code:"RS",code3:"SRB",code4:"381"},
{label:"Seychelles",label2:"Seychelles",label3:"Les Seychelles",code:"SC",code3:"SYC",code4:"248"},
{label:"Sierra Leona",label2:"Sierra Leone",label3:"Sierra Leone",code:"SL",code3:"SLE",code4:"232"},
{label:"Singapur",label2:"Singapore",label3:"Singapour",code:"SG",code3:"SGP",code4:"65"},
{label:"Sint Maarten",label2:"Sint Maarten",label3:"Saint-Martin",code:"SX",code3:"SMX",code4:"1 721"},
{label:"Siria",label2:"Syria",label3:"Syrie",code:"SY",code3:"SYR",code4:"963"},
{label:"Somalia",label2:"Somalia",label3:"Somalie",code:"SO",code3:"SOM",code4:"252"},
{label:"Sri lanka",label2:"Sri Lanka",label3:"Sri Lanka",code:"LK",code3:"LKA",code4:"94"},
{label:"Sudáfrica",label2:"South Africa",label3:"Afrique du Sud",code:"ZA",code3:"ZAF",code4:"27"},
{label:"Sudán",label2:"Sudan",label3:"Soudan",code:"SD",code3:"SDN",code4:"249"},
{label:"Suecia",label2:"Sweden",label3:"Suède",code:"SE",code3:"SWE",code4:"46"},
{label:"Suiza",label2:"Switzerland",label3:"Suisse",code:"CH",code3:"CHE",code4:"41"},
{label:"Surinám",label2:"Suriname",label3:"Surinam",code:"SR",code3:"SUR",code4:"597"},
{label:"Svalbard y Jan Mayen",label2:"Svalbard and Jan Mayen",label3:"Svalbard et Jan Mayen",code:"SJ",code3:"SJM",code4:"47"},
{label:"Swazilandia",label2:"Swaziland",label3:"Swaziland",code:"SZ",code3:"SWZ",code4:"268"},
{label:"Tayikistán",label2:"Tajikistan",label3:"Le Tadjikistan",code:"TJ",code3:"TJK",code4:"992"},
{label:"Tailandia",label2:"Thailand",label3:"Thaïlande",code:"TH",code3:"THA",code4:"66"},
{label:"Taiwán",label2:"Taiwan",label3:"Taiwan",code:"TW",code3:"TWN",code4:"886"},
{label:"Tanzania",label2:"Tanzania",label3:"Tanzanie",code:"TZ",code3:"TZA",code4:"255"},
{label:"Territorio Británico del Océano Índico",label2:"British Indian Ocean Territory",label3:"Territoire britannique de l'océan Indien",code:"IO",code3:"IOT",code4:"246"},
{label:"Territorios Australes y Antárticas Franceses",label2:"French Southern Territories",label3:"Terres australes françaises",code:"TF",code3:"ATF",code4:""},
{label:"Timor Oriental",label2:"East Timor",label3:"Timor-Oriental",code:"TL",code3:"TLS",code4:"670"},
{label:"Togo",label2:"Togo",label3:"Togo",code:"TG",code3:"TGO",code4:"228"},
{label:"Tokelau",label2:"Tokelau",label3:"Tokélaou",code:"TK",code3:"TKL",code4:"690"},
{label:"Tonga",label2:"Tonga",label3:"Tonga",code:"TO",code3:"TON",code4:"676"},
{label:"Trinidad y Tobago",label2:"Trinidad and Tobago",label3:"Trinidad et Tobago",code:"TT",code3:"TTO",code4:"1 868"},
{label:"Tunez",label2:"Tunisia",label3:"Tunisie",code:"TN",code3:"TUN",code4:"216"},
{label:"Turkmenistán",label2:"Turkmenistan",label3:"Le Turkménistan",code:"TM",code3:"TKM",code4:"993"},
{label:"Turquía",label2:"Turkey",label3:"Turquie",code:"TR",code3:"TUR",code4:"90"},
{label:"Tuvalu",label2:"Tuvalu",label3:"Tuvalu",code:"TV",code3:"TUV",code4:"688"},
{label:"Ucrania",label2:"Ukraine",label3:"L'Ukraine",code:"UA",code3:"UKR",code4:"380"},
{label:"Uganda",label2:"Uganda",label3:"Ouganda",code:"UG",code3:"UGA",code4:"256"},
{label:"Uruguay",label2:"Uruguay",label3:"Uruguay",code:"UY",code3:"URY",code4:"598"},
{label:"Uzbekistán",label2:"Uzbekistan",label3:"L'Ouzbékistan",code:"UZ",code3:"UZB",code4:"998"},
{label:"Vanuatu",label2:"Vanuatu",label3:"Vanuatu",code:"VU",code3:"VUT",code4:"678"},
{label:"Venezuela",label2:"Venezuela",label3:"Venezuela",code:"VE",code3:"VEN",code4:"58"},
{label:"Vietnam",label2:"Vietnam",label3:"Vietnam",code:"VN",code3:"VNM",code4:"84"},
{label:"Wallis y Futuna",label2:"Wallis and Futuna",label3:"Wallis et Futuna",code:"WF",code3:"WLF",code4:"681"},
{label:"Yemen",label2:"Yemen",label3:"Yémen",code:"YE",code3:"YEM",code4:"967"},
{label:"Yibuti",label2:"Djibouti",label3:"Djibouti",code:"DJ",code3:"DJI",code4:"253"},
{label:"Zambia",label2:"Zambia",label3:"Zambie",code:"ZM",code3:"ZMB",code4:"260"},
{label:"Zimbabue",label2:"Zimbabwe",label3:"Zimbabwe",code:"ZW",code3:"ZWE",code4:"263"}
]

module.exports = countries